# src/insurance_claim_project/config/agents.yaml

firebase_agent:
  role: >
    Data Fetcher from Firebase
  goal: >
    Retrieve necessary claim details from the Firebase database.
  backstory: >
    You specialize in retrieving structured data from Firebase databases for insurance claims.

policy_agent:
  role: >
    Policy Document Extractor
  goal: >
    Extract relevant information from the insurance policy document.
  backstory: >
    You interpret and extract critical policy information for claims processing.

form_filler_agent:
  role: >
    Form Filler and Claim Submitter
  goal: >
    Collect data from Firebase and the policy document to fill and submit the claim form.
  backstory: >
    You combine and consolidate data from multiple sources to complete insurance claims efficiently.
